#!/bin/sh

usage() {
    printf "usage: %s command [argument...]\n" "$0"
}

if [ $# -lt 1 ]; then
    usage
    exit 2
fi

command=$1
shift

case $command in
    signin)
        ./commands/signin "$@"
        ;;
    list)
        ./commands/list "$@"
        ;;
    *)
        usage
        exit 2
        ;;
esac
